name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install
        working-directory: project
      
      - name: Run tests
        run: npm test
        working-directory: project
      
      - name: Build project (optional)
        run: npm run build
        working-directory: project
      
      - name: Start dev server (as a background job for preview)
        run: nohup npm run dev &
        working-directory: project
